version: '3'

services:
  ap:
    build:
      context: .
    ports:
      - "8080:8080"
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./_postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
